In [1]:
# 지금까지는 python의 리스트를 공부했다
# 하지만 numpy의 '배열' 은 대용량 데이터를 훨씬 더 효과적으로 다룰 수 있다는 점 !
# numpy를 사용한 코드 > 순수 python으로 작성한 코드보다 열 배에서 백 배 이상 빠름

In [4]:
import numpy as np

# 임의의 값을 생성
data = np.random.randn(2,3)
data

array([[ 0.39163647,  1.05572645, -0.44861419],
       [ 0.25248396, -0.21521108, -0.21180503]])

In [5]:
# ndarray는 같은 종류의 데이터를 담을 수 있는 포괄적 다차원 배열
# ndarray의 모든 원소는 같은 자료형이어야 한다

# 차원의 크기를 알려주는 shape이라는 튜플을 가지고 있다
data.shape

(2, 3)

In [6]:
# 배열에 저장된 자료형을 알려주는 dtype이라는 객체
data.dtype

dtype('float64')

In [8]:
# 배열을 생성하는 가장 쉬운 방법 : array 함수 이용

data1 = [6, 7, 8, 7.5, 0, 1] # 리스트

arr1 = np.array(data1)# array 변환

arr1

array([6. , 7. , 8. , 7.5, 0. , 1. ])

In [9]:
# 같은 길이를 가지는 리스트를 내포하는 순차 데이터는 다차원 배열로 변환 가능

data2 = [[1,2,3,4],[5,6,7,8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# 차원 검사

arr2.ndim

2

In [12]:
# shape 검사

arr2.shape

(2, 4)

In [13]:
# np.array는 새로운 배열을 생성하기 위한 여러 함수를 가지고 있다. 

# 주어진 길이에 모두 0이 들어 있는 배열 생성
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# 주어진 길이에 모두 1이 들어 있는 배열 생성
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
# empty 함수는 초기화되지 않은 '가비지' 값으로 채워진 배열 생성
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# arange는 python의 range 함수의 배열 ver.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
# astype 메서드를 활용해서 dtype을 다른 형으로 명시적 변환 가능

# 숫자 형식의 문자열을 담고 있는 배열 --> 숫자로 변환해 보자
numeric_strings = np.array(['1.23', '-9.8', '42'], dtype = np.string_)
numeric_strings.astype(float)

array([ 1.23, -9.8 , 42.  ])